import type { GetStaticProps, NextPage } from "next";
import axios, { AxiosResponse } from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler, MouseEventHandler, useState } from "react";
import styles from "../../styles/pages/Register.module.scss";
import Button from "../../components/base/Button";
import {
  validateEmail,
  validatePassword,
  validateUsername,
} from "../../helpers/validation";
import useInput from "../../hooks/useInput";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

const RegisterPage: NextPage = () => {
  const router = useRouter();
  const { t } = useTranslation();
  const {
    value: username,
    bind: bindUsername,
    reset: resetUsername,
  } = useInput("");
  const { value: email, bind: bindEmail, reset: resetEmail } = useInput("");
  const {
    value: password,
    bind: bindPassword,
    reset: resetPassword,
  } = useInput("");
  const {
    value: confirmPassword,
    bind: bindConfirmPassword,
    reset: resetConfirmPassword,
  } = useInput("");

  const toLoginHandler: MouseEventHandler = (event) => {
    event.preventDefault();
    router.push("/login");
  };

  const submitHandler: FormEventHandler = async (event) => {
    event.preventDefault();

    // simple form validation
    if (!validateUsername(username)) {
      return;
    }
    if (!validateEmail(email)) {
      return;
    }
    if (!validatePassword(password) && password !== confirmPassword) {
      return;
    }

    const payload = {
      name: username,
      email,
      password,
    };

    try {
      const response: AxiosResponse<any, any> = await axios.post(
        "/users",
        payload,
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      const data = response.data;

      console.log(data);

      if (response.status === 201) {
        router.push("/login");
        return;
      }
    } catch (error) {
      console.error(error);
    }
  };

  const resetHandler: FormEventHandler = (event) => {
    event.preventDefault();
    resetUsername();
    resetEmail();
    resetPassword();
    resetConfirmPassword();
  };

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.container}>
        <h1>{t("register:pageTitle")}</h1>
        <form onSubmit={submitHandler} onReset={resetHandler}>
          <div className={styles["input-element"]}>
            <label htmlFor='username'>{t("register:nameLabel")}</label>
            <input
              type='text'
              name='username'
              id='username'
              {...bindUsername}
            />
          </div>
          <div className={styles["input-element"]}>
            <label htmlFor='email'>{t("register:emailLabel")}</label>
            <input type='email' name='email' id='email' {...bindEmail} />
          </div>
          <div className={styles["input-element"]}>
            <label htmlFor='password'>{t("register:passwordLabel")}</label>
            <input
              type='password'
              name='password'
              id='password'
              {...bindPassword}
            />
          </div>
          <div className={styles["input-element"]}>
            <label htmlFor='confirm-password'>
              {t("register:confirmPasswordLabel")}
            </label>
            <input
              type='password'
              name='confirm-password'
              id='confirm-password'
              {...bindConfirmPassword}
            />
          </div>
          <div className={styles.control}>
            <Button type='reset' className='danger'>
              {t("register:resetButton")}
            </Button>
            <Button type='button' className='' onClick={toLoginHandler}>
              {t("register:toLoginLink")}
            </Button>
            <Button type='submit' className='ok'>
              {t("register:registerButton")}
            </Button>
          </div>
        </form>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  locale ?? "en";
  return {
    props: {
      ...(await serverSideTranslations(locale!, ["register"])),
    },
  };
};

export default RegisterPage;
