import type { NextPage } from "next";
import axios, { AxiosResponse } from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler, MouseEventHandler, useState } from "react";
import styles from "../../styles/pages/Register.module.scss";
import Button from "../../components/base/Button";
import { validateEmail, validatePassword } from "../../helpers/validation";
import useInput from "../../hooks/useInput";

const RegisterPage: NextPage = () => {
  const router = useRouter();
  const { value: email, bind: bindEmail, reset: resetEmail } = useInput("");
  const {
    value: password,
    bind: bindPassword,
    reset: resetPassword,
  } = useInput("");
  const {
    value: confirmPassword,
    bind: bindConfirmPassword,
    reset: resetConfirmPassword,
  } = useInput("");

  const toLoginHandler: MouseEventHandler = (event) => {
    event.preventDefault();
    router.push("/login");
  };

  const submitHandler: FormEventHandler = async (event) => {
    event.preventDefault();

    // simple form validation
    if (!validateEmail(email)) {
      return;
    }
    if (!validatePassword(password) && password !== confirmPassword) {
      return;
    }

    const payload = {
      email,
      password,
    };

    const response: AxiosResponse<any, any> = await axios.post(
      "/v1/users",
      payload,
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    if (!response) {
      console.log("Something horrible happened");
    }

    const data = response.data;

    console.log(data);

    if (response.status === 201) {
      router.push("/login");
      return;
    }
  };

  const resetHandler: FormEventHandler = (event) => {
    event.preventDefault();
    resetEmail();
    resetPassword();
    resetConfirmPassword();
  };

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.container}>
        <h1>Register</h1>
        <form onSubmit={submitHandler} onReset={resetHandler}>
          <div className={styles["input-element"]}>
            <label htmlFor='email'>Email</label>
            <input type='email' name='email' id='email' {...bindEmail} />
          </div>
          <div className={styles["input-element"]}>
            <label htmlFor='password'>Password</label>
            <input
              type='password'
              name='password'
              id='password'
              {...bindPassword}
            />
          </div>
          <div className={styles["input-element"]}>
            <label htmlFor='confirm-password'>Confirm Password</label>
            <input
              type='password'
              name='confirm-password'
              id='confirm-password'
              {...bindConfirmPassword}
            />
          </div>
          <div className={styles.control}>
            <Button type='reset' className='danger'>
              Reset
            </Button>
            <Button type='button' className='' onClick={toLoginHandler}>
              To Login
            </Button>
            <Button type='submit' className='ok'>
              Register
            </Button>
          </div>
        </form>
      </div>
    </>
  );
};

export default RegisterPage;
