import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { FormEventHandler } from "react";
import { useSelector } from "react-redux";
import Button from "../../components/base/Button";
import useI18n from "../../hooks/useI18n";
import useInput from "../../hooks/useInput";
import { UsersPageTextType } from "../../i18n/types";
import { State } from "../../store";

import styles from "../../styles/pages/Users.module.scss";

const Users: NextPage = () => {
  const { user: userId } = useSelector((state: State) => state.users);
  const router = useRouter();
  const lang: UsersPageTextType = useI18n(router.locale, router.asPath);

  const { value: typedUserId, bind: bindTypedUserId } = useInput("");

  const searchHandler: FormEventHandler = async (event) => {
    event.preventDefault();

    try {
      await axios.get(`/users/${typedUserId}`);
      router.push("/users/" + typedUserId);
    } catch (err) {
      console.error("an error occurred");
    }
  };

  return (
    <>
      <Head>
        <title>User</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.container}>
        <h1>{lang.title}</h1>
        <Link href={`/users/${userId}`}>{lang.selfDetailsLink}</Link>
        <form onSubmit={searchHandler} className={styles["form"]}>
          <label htmlFor='typedUserId'>{lang.searchLabel}</label>
          <input
            type='text'
            name='typedUserId'
            id='typedUserId'
            {...bindTypedUserId}
          />
          <Button type='submit'>{lang.searchButton}</Button>
        </form>
      </div>
    </>
  );
};

export default Users;
