import type { NextPage } from "next";
import Head from "next/head";

const User: NextPage = () => {
  return (
    <>
      <Head>
        <title>User</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>User</main>
    </>
  );
};

export default User;
