import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import PostList from "../../components/blog/postList";
import { PostType } from "../../models/models";

const BlogPage: NextPage = () => {
  const [posts, setPosts] = useState<PostType[]>([]);

  useEffect(() => {
    (async () => {
      const response = await fetch("https://testapi.schattenbrot.com/v1/posts");
      const data: PostType[] = await response.json();
      setPosts(data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Blog</h1>
        <PostList posts={posts} />
      </main>
    </>
  );
};

export default BlogPage;
