import type { NextPage } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";
import { State } from "../store";
import styles from "../styles/pages/Home.module.scss";

const Home: NextPage = () => {
  const { user: userId } = useSelector((state: State) => state.users);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className={styles.title}>Home {userId && "- " + userId}</h1>
      </main>
    </>
  );
};

export default Home;
