import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";
import { State } from "../store";
import styles from "../styles/pages/Home.module.scss";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

const Home: NextPage = () => {
  const { t } = useTranslation();
  const { user: userId } = useSelector((state: State) => state.users);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className={styles.title}>
          {t("home:welcome")} {userId && userId}
        </h1>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  locale ?? "en";
  return {
    props: {
      ...(await serverSideTranslations(locale!, ["home"])),
    },
  };
};

export default Home;
